# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: siyan_api_dev

production:
  <<: *default
  host: siyan-api.ci10biwxfecs.us-east-1.rds.amazonaws.com
  username: siyan
  password: trance85
  database: homepage
